[project]
name = "itempoolapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "pydantic>=2.11.7",
    "pymongo>=4.15.3",
    "sqlglot>=27.29.0",
    "textstat>=0.7.11",
    "sqlacodegen==4.0.3",
    "psycopg2-binary>=2.9.12",
    "sqlmodel>=0.0.38",
    "python-dotenv>=1.1.1",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
]
