### Voraussetzung: Es existieren bereits Items (z. B. via dummydaten/INITIAL_FILL.http)

### 1) Collection aus bestehenden Item-IDs anlegen
POST {{baseUrl}}/createItemCollection
Content-Type: application/json

{
  "name": "Klausurpool SQL SS26",
  "item_ids": [1, 2]
}

###
### 2) Alle Collections abrufen
GET {{baseUrl}}/getAllItemCollections

###
### 3) Einzelne Collection per ID abrufen
GET {{baseUrl}}/getItemCollection/1

###
### 4) Collection aktualisieren (Name und Item-IDs ändern)
PUT {{baseUrl}}/updateItemCollection/1
Content-Type: application/json

{
  "name": "SQL Grundlagen SS26 - Updated",
  "item_ids": [1, 2, 3]
}

###
### 5) Collection löschen
DELETE {{baseUrl}}/deleteItemCollection/1

